package stocktales.enums;

public enum SCSScoreCalibrationHeaders {
	ValueRatioCalibration, UnpledgedPromoterHoldingCalibration, WorkingCapitalCycleCalibration,
	CFOPATAdherenceCalibration, InterestDepriciationByPATCalibration, FinancialSectorBaseBooster,
	FinancialSectorBestBooster, FinancialSectorROEBooster
}
